export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const SET_DEFAULT_MODE = 'SET_DEFAULT_MODE';
export const SET_TITLE = 'SET_TITLE';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
